spring.application.name=portfolio-app

# ====== Подключение к PostgreSQL ======
spring.datasource.url=jdbc:postgresql://localhost:5432/photographer_portfolio
spring.datasource.username=postgres
spring.datasource.password=3211Boy9_123

# ====== JPA ======
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SMTP для Gmail (пример; для других провайдеров меняются host/port)
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Ваш адрес и пароль (для Gmail — сгенерируйте App Password в настройках аккаунта)
spring.mail.username=roma.borisenko2004@gmail.com
spring.mail.password=hdyx xkat nlmn jann

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Куда шлём письма — тот же адрес
app.photographer.email=roma.borisenko2004@gmail.com



# TODO: В продакшене использовать пул соединений (HikariCP) и вынести секреты в переменные окружения


